# Generated by Django 4.1.1 on 2022-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='bookid',
            field=models.IntegerField(default=1, verbose_name=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='is_available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
