# Generated by Django 4.1.1 on 2022-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_library_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='bookid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='is_available',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
