# Generated by Django 4.1.1 on 2022-09-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_library_bookid_library_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='bookid',
        ),
    ]
