# Generated by Django 4.1.1 on 2022-09-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_library_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_available',
        ),
    ]
